version: "3.9"

services:
#  keycloak:
#    build: solana-sign-in-keycloak
#    ports:
#      - "8080:8080"
  backend:
    build: solana-sign-in-backend
    ports:
      - "8081:8081"
  bff:
    build: solana-sign-in-bff
    ports:
      - "8082:8082"
